export const TYPES = {
    IMerchantRepository: Symbol.for("IMerchantRepository"),
    IQuoteRepository: Symbol.for("IQuoteRepository"),
    IPlanRepository: Symbol.for("IPlanRepository"),
    IMerchantService: Symbol.for("IMerchantService"),
    IQuoteService: Symbol.for("IQuoteService"),
    IPlanService: Symbol.for("IPlanService"),
    IEmailService: Symbol.for("IEmailService"),
    ISettingsService: Symbol.for("ISettingsService"),
    IDraftOrderService: Symbol.for("IDraftOrderService"),
    IUsageService: Symbol.for("IUsageService"),
    IWebhookRegistry: Symbol.for("IWebhookRegistry"),
    AuthController: Symbol.for("AuthController"),
    QuoteController: Symbol.for("QuoteController"),
    WebhooksController: Symbol.for("WebhooksController"),
    MerchantController: Symbol.for("MerchantController"),
    SettingsController: Symbol.for("SettingsController"),
    DraftOrderController: Symbol.for("DraftOrderController"),
    DraftOrderMapper: Symbol.for("DraftOrderMapper"),
    PlanController: Symbol.for("PlanController"),
};
